altcha:
    enable: true
    hmacSignature: '%env(APP_SECRET)%' # Replaces deprecated hmacKey
    hmacAlgorithm: 'SHA-256'
    hmacKeySignature: ~ # Optional signature key
    cost: 5000
    counter_min: 5000
    counter_max: 10000
    timeout: 30.0
    floating: true
    overlay: false
    use_stimulus: false
    include_script: true
    hide_logo: false
    hide_footer: false

when@test:
    altcha:
        enable: false