services:
    app:
        container_name: ${PROJECT_SLUG}-app
        build:
            context: .docker
            dockerfile: php.dockerfile
        restart: unless-stopped
        expose:
            - "9000"
        ports:
            - "5678:5678"
        volumes:
            - ./:/var/www/html
        networks:
            - thedarknine-ntwk
        depends_on:
            - db

    db:
        container_name: ${PROJECT_SLUG}-db
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - thedarknine-ntwk
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
            - ./.docker/volumes/logs/mysql:/var/log/mysql
            - ./.docker/mysql/sql:/docker-entrypoint-initdb.d
            - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

    engine:
        container_name: ${PROJECT_SLUG}-server
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - thedarknine-ntwk

    pma:
        image: arm64v8/phpmyadmin:latest
        container_name: ${PROJECT_SLUG}-pma
        ports:
            - 8088:80
        depends_on:
            - db
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        networks:
            - thedarknine-ntwk
    
    mailpit:
        image: axllent/mailpit:latest
        container_name: ${PROJECT_SLUG}-mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        environment:
            - MP_SMTP_AUTH_ACCEPT_ANY=1
            - MP_SMTP_AUTH_ALLOW_INSECURE=1
        networks:
            - thedarknine-ntwk
    
    # To run Panther tests
    chrome:
        image: seleniarm/standalone-chromium:latest
        container_name: ${PROJECT_SLUG}-chrome
        volumes:
            - /dev/shm:/dev/shm # Avoid Chrome memory crashes
        ports:
            - "4444:4444"
        networks:
            - thedarknine-ntwk

networks:
    thedarknine-ntwk:
        driver: bridge
        name: ${PROJECT_SLUG:-nine}ntwk 
