allowBuilds:
  '@parcel/watcher': false
  chromedriver: false
  esbuild: true
  puppeteer: true
  vue-demi: false
minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - '@opentelemetry/core@2.8.0'
  - js-yaml@3.15.0
