# .tools/checkmake.ini
[default]
format = "{{.LineNumber}}:{{.Rule}}:{{.Violation}}"

[maxbodylength]
disabled = true # Because Makefile uses ONESHELL

[minphony]
disabled = true # Because no `all` target is needed